### PR TITLE
Revert "Update ParserHooks.php"

### PR DESCRIPTION
**Pull request by JeroenDeDauw**
Reverts JeroenDeDauw/ParserHooks#4

### CODE REVIEW

**Comment by JeroenDeDauw** [comment]
Autoloading is done via composer, not manual MediaWiki classmap

**Comment by paladox** [comment]
Hi it keeps erroring out

17:16:54 PHP Fatal error:  Class 'ParserHooks\HookRunner' not found in /mnt/jenkins-workspace/workspace/mwext-ParserHooks-testextension-zend/src/extensions/ParserHooks/tests/phpunit/HookRunnerTest.php on line 26

at https://integration.wikimedia.org/ci/job/mwext-ParserHooks-testextension-zend/11/console

**Comment by JeroenDeDauw** [comment]
I'm going to assume this is because the Jenkins setup there is broken. It works on Travis, and I can run the tests locally

**Comment by paladox** [comment]
Oh jenkins isent broken since it is on Wikimedia. And works with most extensions.

**Comment by paladox** [comment]
Works with this new test https://integration.wikimedia.org/ci/job/mwext-testextension-zend-composer/173/console

its because Wikimedia haven several test so the zend-composer test works.

**Comment by paladox** [comment]
@JeroenDeDauw Please can you review https://gerrit.wikimedia.org/r/#/c/247864/ it is to fix jenkins test keep failing and imports code from here.

**Pull request merged**
