### PR TITLE
Update HookRegistrant.php

### PR DESCRIPTION
**Pull request by paladox**
Updated here https://git.wikimedia.org/commitdiff/mediawiki%2Fextensions%2FParserHooks/613f6c780e86a2e8c4b3d71199b9c074f14ad3e1

### CODE REVIEW

**Comment by JeroenDeDauw** [comment]
Ah... this is not how you sync git repo... you just create merge conflicts and mess up git blame

**Comment by paladox** [comment]
Oh ok. I am not sure how to then.

**Comment by JeroenDeDauw** [comment]
Like #10. I recommend you read up on how git remotes work

**Comment by paladox** [comment]
Ok.

**Pull request closed without merging**
